### ISSUE TITLE
Erreur de provisionning à l'installation

### ISSUE THREAD

**Issue by cyrilvignon** [sgmap/openfisca-loiret#1]
erreur durant une installation de type mes-aides stack

[install_mes-aides_20170906.txt](https://github.com/sgmap/openfisca-cd45/files/1281150/install_mes-aides_20170906.txt)

**Comment by guillett** [comment]
Le setup de la stack mes-aides n'est pas nécessaire pour le développement de l'extension pour le Loiret. J'ai commencé à regarder les logs envoyés mais je n'ai pas trouvé la solution pour le moment.

Est-il possible de lancer les commandes suivantes, à la place du code de [mes-aides-ops](https://github.com/sgmap/mes-aides-ops) ?

Elles permettent d'installer et de tester l'extension.
```sh
virtualenv venv
source venv/bin/activate
pip install --upgrade pip

git clone https://github.com/sgmap/openfisca-loiret.git
cd openfisca-loiret/
pip install --editable .[test]
source ../venv/bin/activate

make test
```

**Comment by guillett** [comment]
@cyrilvignon comme vu ensemble. Les instructions indiquées dans mon message précédent ont permise :
- d'installer l'extension et ses dépendances,
- de lancer les tests et de les faire passer et
- de décrire l'architecture typique d'une extension et ses différentes parties.

Je ferme cet issue mais je garde le problème visible sur https://github.com/sgmap/mes-aides-ops/issues/54.
